### ISSUE TITLE
Doesn't spawn process

### ISSUE THREAD

**Issue by igidas** [royriojas/precommit#5]
Hey, I can't get this package working on Windows.

In my package.json I have `"precommit": ["npm run lint"]`, but it gives me ENOENT error.
Tried to debug precommit hook and looks like working dir which spawned script uses is '.git/hooks' instead of project root folder.

**Comment by royriojas** [comment]
@igidas mmm that is interesting, can you please post your error log?

**Comment by MundakaZgz** [comment]
Hi there,

I am having the same issue. In my case the task I am running is `eslint . --ext .json`.
The whole output is:

> git commit -m "Tests pre-commit hook"
> applying precommit on branch  pre-commit-check
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> Error: spawn npm ENOENT
>     at exports._errnoException (util.js:1022:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:359:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

Thanks!
